RoastSoftware/roaster

.gitignore, .travis.yml, Procfile
encrypted credentials, this might need changes.
=> ci: add automatic deploy to AWS using Travis CI

doc/architecture/stack.png
=> doc: front end stack visualization

README.md
Add some instructions for setting up the development environment.
Updates: #57
=> doc: add preliminary instructions for setting up dev-env (updates: #57)

doc/postgresql/roaster-database-v0.0.1.png, doc/postgresql/roaster-database-v0.0.1.sql, doc/postgresql/roaster-database-v0.0.1.uml
Initial database with the user, roast, error and warning tables.
Fixes: #13
=> doc/postgresql: add database w/ initial tables (fixes: #13)

www/src/models/user.ts, www/src/views/login.ts
=> correct api paths (fixes: #100)

www/src/views/home.ts
=> www/src/views: add border to message column

doc/architecture/security.md
Initial documentation of security measures.
=> doc/architecture: security documentation (fixes: #106)

doc/restapi/Roaster-REST-API.md
=> doc/restapi: update documentation for REST API since #104

doc/postgresql/roaster-database-v0.0.2.sql, model/forwardengineer/schema.go, model/roast.go, www/src/models/editor.ts, www/src/views/editor.ts, www/src/views/home.ts
=> doc+model+www: display roast result in frontend (fixes #128)

controller/roast/roast.go
=> controller/roast: allow unregistered users to get roasted (fixes: #136)

www/src/index.ts, www/src/models/statistics.ts, www/src/views/about.ts, www/src/views/login.ts, www/src/views/profile.ts, www/src/views/user.ts
This branch will fix the about page and the user pages.
=> www/src: about page and user page

doc/restapi/Roaster-REST-API.md, router/route/static.go, router/router.go, tool/build-production.sh
=>  doc+router+tool: add online REST API docs at /doc/restapi 

doc/postgresql/roaster-database-v0.0.2.sql, doc/restapi/Roaster-REST-API.md, model/forwardengineer/schema.go, model/roast.go, model/user.go, router/route/user.go, www/src/models/user.ts, www/src/views/login.ts, www/src/views/profile.ts, www/src/views/user.ts
So far table for user_friends is implemented.
=> database model for friends 

model/feed.go, model/statistics.go, router/route/feed.go, router/route/session.go, router/route/statistics.go, session/session.go, www/src/models/statistics.ts, www/src/views/feed.ts
* session: return error for Invalidate.
* {router/route,model}/{feed,statistics}: add `?friends=true` query parameter
+ www/src/models/statistics: fix wrong label for errors and warnings in doughnut chart
+ www/src/views/feed: fix invalid switch statement for filter
Fixes: #176 
Fixes: #167
=> session+router/route+model+www: add `?friends=true` query parameter and minor bugs

analyze/flake8.go
=> analyze/flake8: use flake8Result instead of whole model.RoastResult

router/route/roast.go, www/src/views/home.ts
=> router/route/roast+www: handle too large snippet RESTfully and add frontend messages and loading indicator

www/src/views/editor.ts
This was easier than I thought :smile:
=> www/src/views/editor: do not overwrite code if already set (fixed: #179)

doc/postgresql/roaster-database-v0.0.2.sql, model/forwardengineer/schema.go, www/src/views/user.ts
=> www/src/user: fix followee/follower regression since #206

doc/restapi/Roaster-REST-API.md, router/route/search.go, www/src/views/nav.ts
=> doc+router+www: add updated API docs, fix search query 404 bug

tool/build-production.sh, www/package-lock.json
=> tool: switch to aglio for rendering REST docs

README.md
=> doc: add godoc.org badge

doc/screenshots/Screenshot_2019-08-11 Get Roasted - Roaster Inc Feed.png, doc/screenshots/Screenshot_2019-08-11 Get Roasted - Roaster Inc Homepage.png, doc/screenshots/Screenshot_2019-08-11 Get Roasted - Roaster Inc Profile.png
=> doc/screenshots: add screenshots of some pages

README.md
+ The PR title is formatted as follows: `controller/static: frob the quux before blarfing`
+ The package name goes before the colon
+ The part after the colon uses the verb tense + phrase that completes the blank in,
"This change modifies Roaster to ___________"
+ Lowercase verb after the colon
+ No trailing period
+ Keep the title as short as possible. ideally under 76 characters or shorter
+ No Markdown
+ The first PR comment (this one) is wrapped at 76 characters, unless it's
really needed (ASCII art, table, or long link)
+ If there is a corresponding issue, add either `(fixes #1234)` or `(updates #1234)`
(the latter if this is not a complete fix) to this comment
=> doc: add project report links to README.md
